### PR TITLE
YCSB support

### PR DESCRIPTION
**Pull request by tzach**
This PR add YCSB support to the project.
To use:
- create loader with ycsb tags: ``` ./ec2-setup-loadgen.sh -e "load_nodes=2" -e "instance_type=c3.xlarge" -e "ycsb=true" ```
- run YCSB load: ```./ec2-stress-ycsb.sh 1 -e "load_name=scylla.v14" -e "server=Scylla" -e "prepere_options='-p recordcount=100000'" -e "run_options='-p operationcount=1000 -p cassandra.writeconsistencylevel=QUORUM -p cassandcra.readconsistencylevel=QUORUM -p operationcount=100'"```

YCSB test, like cassandra-stress, respect the `seq_populate` option to run different range from each loader

### CODE REVIEW

**Comment by tzach** [comment]
@nirmaayan can you review and test this PR? thanks

**Comment by nirmaayan** [comment]
sure

**Comment by nirmaayan** [comment]
PR tested
I run the YCSB using one Scylla and one loader

Commands that I used:
./ec2-setup-loadgen.sh -e "load_nodes=1" -e "instance_type=m3.medium" -e "ycsb=true"

./ec2-setup-scylla.sh -e "cluster_nodes=1" -e "instance_type=m3.medium" -e "prometheus_client=true"

./ec2-stress-ycsb.sh 1 -e "load_name=scylla.v14" -e "server=Scylla" -e "prepere_options='-p recordcount=1000000'" -e "run_options='-p operationcount=10000 -p cassandra.writeconsistencylevel=QUORUM -p cassandcra.readconsistencylevel=QUORUM -p operationcount=1000'"

**Comment by tzach** [comment]
Thanks @nirmaayan 
does the results make sense?

**Pull request merged**
